networks:
  app-network:
    driver: bridge

services:
  mongo:
    image: mongo:7
    container_name: mongoDB
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-lactokeeper}
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    container_name: backend_lactokeeper
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/lactokeeper}
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    container_name: frontend_lactokeeper
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:5001}
      - INTERNAL_API_URL=${INTERNAL_API_URL:-http://backend:5001}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-unaclavesecretabuenaParagenerarTokens1234}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXT_PUBLIC_WSS_URL=${NEXT_PUBLIC_WSS_URL:-ws://localhost:5001}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo_data:
